#use_frameworks!

platform :ios, '9.0'

inhibit_all_warnings!

target 'ADNetwork_Example' do
  pod 'ADNetwork', :path => '../'
  
#  post_install do |installer|
#      installer.pods_project.targets.each do |target|
#          target.build_configurations.each do |config|
#              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
#          end
#      end
#  end

  target 'ADNetwork_Tests' do
    inherit! :search_paths

    
  end
end
